#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 4
bspc config window_gap 5

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

pkill picom
picom &

pkill polybar
polybar &

pkill dunst
dunst &

pkill xfce-polkit
/usr/lib/xfce-polkit/xfce-polkit &

~/.fehbg &
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
xsetroot -cursor_name left_ptr

bspc rule -a Alacritty state=floating follow=on
bspc rule -a TelegramDesktop state=floating follow=on
bspc rule -a Thunar state=floating follow=on
bspc rule -a Google-chrome desktop='^2' follow=on
bspc rule -a Code desktop='^1' follow=on
bspc rule -a Postman desktop='^3' follow=on
bspc rule -a whatsdesk state=floating follow=on
bscp rule -a Spotify desktop='^5' follow=on
bspc rule -a Gnome-screenshot state=floating follow=on
bspc rule -a Ristretto state=floating
bspc rule -a discord state=floating

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
